spring:
  application:
    name: tbd
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none    # Changed from 'create' to 'none' to prevent table recreation
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.default_schema: bikersdream
      hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: false     # To prevent SQL queries from being printed in the console
  flyway:
    enabled: true
    locations: classpath:db/migration
    defaultSchema: bikersdream
    baseline-on-migrate: true

logging:
  level:
    com.soen343.tbd: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: INFO
    com.zaxxer.hikari.pool.HikariPool: WARN
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{40} | %msg%n"
    
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    